name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-lint-npm-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install Deps
        run: npm i
        
      - name: Fmt
        run: npm run check-fmt
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-npm-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install Deps
        run: npm i
        
      - name: Build
        run: npm run build
