name: Website
on:
  push:
    branches:
      - master

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-lint-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Deps
        run: npm i

      - name: Build
        run: npm run build
        
      - name: Add Bing Site Verification
        run: echo "$BING_SITE_AUTH_XML" > ./dist/BingSiteAuth.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
